- hosts: all
  become: true
  become_method: sudo
  tasks:

    - name: Get Top 5 CPU consuming processes
      shell: ps aux | sort -nrk 3,3 | head -n 5
      register: top

    - debug: var=top.stdout_lines
